spring:
  datasource:
    name: tibetan
    url: jdbc:mysql://localhost:3306/tibetan
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20 
  thymeleaf:
    cache: false
    cache-period: 0
  template:
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    
mybatis: 
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.huang.TibetanLibrary.domain 