package com.huang.TibetanLibrary.util;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class FontUtil {
	
	/**
	 * 前加字
	 */
	public static Map<String, String>  PREFIXSET = new HashMap<String, String>();
	static{
		PREFIXSET.put("ག", "ɡ");
		PREFIXSET.put("ད", "d");
		PREFIXSET.put("བ", "b");
		PREFIXSET.put("མ", "m");
		PREFIXSET.put("འ", "v");
	}
	
	/**
	 * 上加字
	 */
	public static Map<String, String> SUPERSCRIPTSET = new HashMap<String, String>();
	static{
		SUPERSCRIPTSET.put("ར", "r");
		SUPERSCRIPTSET.put("ྲ", "r");
		SUPERSCRIPTSET.put("ལ", "l");
		SUPERSCRIPTSET.put("ས", "s");
	}
	
	/**
	 * 
	 */
	public static Map<String, String> VOWELSET= new HashMap<String, String>();
	static{
		VOWELSET.put("ི", "i");
		VOWELSET.put("ུ", "u");
		VOWELSET.put("ེ", "e");
		VOWELSET.put("ོ", "o");
	}
	
	public static Map<String, String> VOWELUPSET= new HashMap<String, String>();
	static{
		VOWELUPSET.put("ི", "i");
		VOWELUPSET.put("ེ", "e");
		VOWELUPSET.put("ོ", "o");
	}
	
	public static Map<String, String> VOWELDOWNSET= new HashMap<String, String>();
	static{
		VOWELDOWNSET.put("ུ", "u");
	}
	
	/**
	 * 下加字
	 */
	public static Map<String, String> SUBSCRIPTSET = new HashMap<String, String>();
	static{
		SUBSCRIPTSET.put("འ", "v");
		SUBSCRIPTSET.put("ཡ", "y");
		SUBSCRIPTSET.put("ར", "r");
		SUBSCRIPTSET.put("ྲ", "r");
		SUBSCRIPTSET.put("ལ", "l");
		SUBSCRIPTSET.put("ླ", "l");
		SUBSCRIPTSET.put("ཝ", "w");
		SUBSCRIPTSET.put("ྱ", "y");
		SUBSCRIPTSET.put("གྲྷ", "");
	}
	
	public static Map<String, String> INTERNATIONALPHONETICALPHABETSET = new HashMap<String, String>();
	static{
		INTERNATIONALPHONETICALPHABETSET.put("ཀ", "k");
		INTERNATIONALPHONETICALPHABETSET.put("ཁ", "kh");
		INTERNATIONALPHONETICALPHABETSET.put("ག", "ɡ");
		INTERNATIONALPHONETICALPHABETSET.put("ང", "ŋ");
		INTERNATIONALPHONETICALPHABETSET.put("ཅ", "ʨ");
		INTERNATIONALPHONETICALPHABETSET.put("ཆ", "ʨh");
		INTERNATIONALPHONETICALPHABETSET.put("ཇ", "ʤ");
		INTERNATIONALPHONETICALPHABETSET.put("ཉ", "ȵ");
		INTERNATIONALPHONETICALPHABETSET.put("ཏ", "t");
		INTERNATIONALPHONETICALPHABETSET.put("ཐ", "th");
		INTERNATIONALPHONETICALPHABETSET.put("ད", "d");
		INTERNATIONALPHONETICALPHABETSET.put("ན", "n");
		INTERNATIONALPHONETICALPHABETSET.put("ྷ", "h");		
		INTERNATIONALPHONETICALPHABETSET.put("པ", "p");
		INTERNATIONALPHONETICALPHABETSET.put("ཕ", "ph");
		INTERNATIONALPHONETICALPHABETSET.put("བ", "b");
		INTERNATIONALPHONETICALPHABETSET.put("མ", "m");
		INTERNATIONALPHONETICALPHABETSET.put("ཙ", "ʦ");
		INTERNATIONALPHONETICALPHABETSET.put("ཚ", "ʦh");
		INTERNATIONALPHONETICALPHABETSET.put("ཛ", "ʣ");
		INTERNATIONALPHONETICALPHABETSET.put("ཝ", "w");
		INTERNATIONALPHONETICALPHABETSET.put("ཞ", "ʑ");
		INTERNATIONALPHONETICALPHABETSET.put("ཟ", "z");
		INTERNATIONALPHONETICALPHABETSET.put("འ", "v");
		INTERNATIONALPHONETICALPHABETSET.put("ཡ", "j");
		INTERNATIONALPHONETICALPHABETSET.put("ར", "r");
		INTERNATIONALPHONETICALPHABETSET.put("ལ", "l");
		INTERNATIONALPHONETICALPHABETSET.put("ཤ", "");
		INTERNATIONALPHONETICALPHABETSET.put("ས", "s");
		INTERNATIONALPHONETICALPHABETSET.put("ཧ", "h");
		INTERNATIONALPHONETICALPHABETSET.put("ཨ", "");
		INTERNATIONALPHONETICALPHABETSET.put("ི", "i");
		INTERNATIONALPHONETICALPHABETSET.put("ུ", "u");
		INTERNATIONALPHONETICALPHABETSET.put("ེ", "e");
		INTERNATIONALPHONETICALPHABETSET.put("ོ", "o");
	}
	
	public static Map<String, String> WILLIESET = new HashMap<String, String>();
	static{
		WILLIESET.put("f40", "k");
		WILLIESET.put("f41", "kh");
		WILLIESET.put("f42", "ɡ");
		WILLIESET.put("f43", "ɡh");
		WILLIESET.put("f44", "nɡ");
		WILLIESET.put("f45", "c");
		WILLIESET.put("f46", "ch");
		WILLIESET.put("f47", "j");
		WILLIESET.put("f49", "ny");
		WILLIESET.put("f4f", "t");
		WILLIESET.put("f50", "th");
		WILLIESET.put("f51", "d");
		WILLIESET.put("f52", "dh");
		WILLIESET.put("f53", "n");
		WILLIESET.put("f54", "p");
		WILLIESET.put("f55", "ph");
		WILLIESET.put("f56", "b");
		WILLIESET.put("f57", "bh");
		WILLIESET.put("f58", "m");
		WILLIESET.put("f59", "ʦ");
		WILLIESET.put("f5a", "ʦh");
		WILLIESET.put("f5b", "ʣ");
		WILLIESET.put("f5c", "dzh");
		WILLIESET.put("f5d", "w");
		WILLIESET.put("f5e", "zh");
		WILLIESET.put("f5f", "z");
		WILLIESET.put("f60", "v");
		WILLIESET.put("f61", "y");
		WILLIESET.put("f62", "r");
		WILLIESET.put("f63", "l");
		WILLIESET.put("f64", "sh");
		WILLIESET.put("f66", "s");
		WILLIESET.put("f67", "h");
		WILLIESET.put("f68", " ");
		WILLIESET.put("f62", "r");
		WILLIESET.put("fb0", "v");
		WILLIESET.put("f72", "i");
		WILLIESET.put("f73", "i v");
		WILLIESET.put("f74", "u");
		WILLIESET.put("f75", "vu");
		WILLIESET.put("f7a", "e");
		WILLIESET.put("f7c", "o");
		WILLIESET.put("f90", "k");
		WILLIESET.put("f91", "kh");
		WILLIESET.put("f92", "ɡ");
		WILLIESET.put("f93", "ɡh");
		WILLIESET.put("f94", "nɡ");
		WILLIESET.put("f95", "c");
		WILLIESET.put("f96", "ch");
		WILLIESET.put("f97", "j");
		WILLIESET.put("f99", "ny");
		WILLIESET.put("f9f", "t");
		WILLIESET.put("fa0", "th");
		WILLIESET.put("fa1", "d");
		WILLIESET.put("fa2", "dh");
		WILLIESET.put("fa3", "n");
		WILLIESET.put("fa4", "p");
		WILLIESET.put("fa5", "ph");
		WILLIESET.put("fa6", "b");
		WILLIESET.put("fa7", "bh");
		WILLIESET.put("fa8", "m");
		WILLIESET.put("fa9", "ʦ");
		WILLIESET.put("faa", "ʦh");
		WILLIESET.put("fab", "ʣ");
		WILLIESET.put("fac", "dzh");
		WILLIESET.put("fad", "w");
		WILLIESET.put("fae", "zh");
		WILLIESET.put("faf", "z");
		WILLIESET.put("fb0", "v");
		WILLIESET.put("fb1", "y");
		WILLIESET.put("fb2", "r");
		WILLIESET.put("fb3", "l");
		WILLIESET.put("fb4", "sh");
		WILLIESET.put("fb6", "s ");
		WILLIESET.put("fb7", "h");
		WILLIESET.put("fba", "w");
		WILLIESET.put("fbb", "y");
		WILLIESET.put("fbc", "r");
	}
	
	public static Set<String> EXHAUSTIVESET = new HashSet<String>();
	static{
		EXHAUSTIVESET.add("ka");
		EXHAUSTIVESET.add("kwaɡ");
		EXHAUSTIVESET.add("kyaɡs");
		EXHAUSTIVESET.add("kranɡ");
		EXHAUSTIVESET.add("klanɡs");
		EXHAUSTIVESET.add("dkad");
		EXHAUSTIVESET.add("dkyan");
		EXHAUSTIVESET.add("dkrand");
		EXHAUSTIVESET.add("bkab");
		EXHAUSTIVESET.add("bkyabs");
		EXHAUSTIVESET.add("bkram");
		EXHAUSTIVESET.add("bklams");
		EXHAUSTIVESET.add("rkar");
		EXHAUSTIVESET.add("rkyard");
		EXHAUSTIVESET.add("lkal");
		EXHAUSTIVESET.add("skald");
		EXHAUSTIVESET.add("skyas");
		EXHAUSTIVESET.add("skravo");
		EXHAUSTIVESET.add("brkavi");
		EXHAUSTIVESET.add("brkyavu");
		EXHAUSTIVESET.add("bski");
		EXHAUSTIVESET.add("bskyiɡ");
		EXHAUSTIVESET.add("bskriɡs");
		EXHAUSTIVESET.add("khinɡ");
		EXHAUSTIVESET.add("khwinɡs");
		EXHAUSTIVESET.add("khyid");
		EXHAUSTIVESET.add("khrin");
		EXHAUSTIVESET.add("mkhind");
		EXHAUSTIVESET.add("mkhyib");
		EXHAUSTIVESET.add("mkhribs");
		EXHAUSTIVESET.add("vkhim");
		EXHAUSTIVESET.add("vkhyims");
		EXHAUSTIVESET.add("vkhrir");
		EXHAUSTIVESET.add("ɡird");
		EXHAUSTIVESET.add("ɡwil");
		EXHAUSTIVESET.add("ɡyild");
		EXHAUSTIVESET.add("ɡris");
		EXHAUSTIVESET.add("ɡrwivo");
		EXHAUSTIVESET.add("ɡlivi");
		EXHAUSTIVESET.add("dɡivu");
		EXHAUSTIVESET.add("dɡyu");
		EXHAUSTIVESET.add("dɡruɡ");
		EXHAUSTIVESET.add("bɡuɡs");
		EXHAUSTIVESET.add("bɡyunɡ");
		EXHAUSTIVESET.add("bɡrunɡs");
		EXHAUSTIVESET.add("mɡud");
		EXHAUSTIVESET.add("mɡyun");
		EXHAUSTIVESET.add("mɡrund");
		EXHAUSTIVESET.add("vɡub");
		EXHAUSTIVESET.add("vɡyubs");
		EXHAUSTIVESET.add("vɡrum");
		EXHAUSTIVESET.add("rɡums");
		EXHAUSTIVESET.add("rɡyur");
		EXHAUSTIVESET.add("lɡurd");
		EXHAUSTIVESET.add("sɡul");
		EXHAUSTIVESET.add("sɡyuld");
		EXHAUSTIVESET.add("sɡrus");
		EXHAUSTIVESET.add("brɡuvo");
		EXHAUSTIVESET.add("brɡyuvi");
		EXHAUSTIVESET.add("bsɡuvu");
		EXHAUSTIVESET.add("bsɡye");
		EXHAUSTIVESET.add("bsɡreɡ");
		EXHAUSTIVESET.add("nɡeɡs");
		EXHAUSTIVESET.add("dnɡenɡ");
		EXHAUSTIVESET.add("mnɡenɡs");
		EXHAUSTIVESET.add("rnɡed");
		EXHAUSTIVESET.add("lnɡen");
		EXHAUSTIVESET.add("snɡend");
		EXHAUSTIVESET.add("brnɡeb");
		EXHAUSTIVESET.add("bsnɡebs");
		EXHAUSTIVESET.add("cem");
		EXHAUSTIVESET.add("ɡcems");
		EXHAUSTIVESET.add("bcer");
		EXHAUSTIVESET.add("lcerd");
		EXHAUSTIVESET.add("chel");
		EXHAUSTIVESET.add("mcheld");
		EXHAUSTIVESET.add("vches");
		EXHAUSTIVESET.add("jevo");
		EXHAUSTIVESET.add("mjevi");
		EXHAUSTIVESET.add("vjevu");
		EXHAUSTIVESET.add("rjo");
		EXHAUSTIVESET.add("ljoɡ");
		EXHAUSTIVESET.add("brjoɡs");
		EXHAUSTIVESET.add("nyonɡ");
		EXHAUSTIVESET.add("nywonɡs");
		EXHAUSTIVESET.add("ɡnyod");
		EXHAUSTIVESET.add("mnyon");
		EXHAUSTIVESET.add("rnyond");
		EXHAUSTIVESET.add("snyob");
		EXHAUSTIVESET.add("brnyobs");
		EXHAUSTIVESET.add("bsnyom");
		EXHAUSTIVESET.add("toms");
		EXHAUSTIVESET.add("tror");
		EXHAUSTIVESET.add("ɡtord");
		EXHAUSTIVESET.add("btol");
		EXHAUSTIVESET.add("rtold");
		EXHAUSTIVESET.add("ltos");
		EXHAUSTIVESET.add("stovo");
		EXHAUSTIVESET.add("brtovi");
		EXHAUSTIVESET.add("bltovu");
		EXHAUSTIVESET.add("k");
		EXHAUSTIVESET.add("kw");
		EXHAUSTIVESET.add("ky");
		EXHAUSTIVESET.add("kr");
		EXHAUSTIVESET.add("kl");
		EXHAUSTIVESET.add("dk");
		EXHAUSTIVESET.add("dky");
		EXHAUSTIVESET.add("dkr");
		EXHAUSTIVESET.add("bk");
		EXHAUSTIVESET.add("bky");
		EXHAUSTIVESET.add("bkr");
		EXHAUSTIVESET.add("bkl");
		EXHAUSTIVESET.add("rk");
		EXHAUSTIVESET.add("rky");
		EXHAUSTIVESET.add("lk");
		EXHAUSTIVESET.add("sk");
		EXHAUSTIVESET.add("sky");
		EXHAUSTIVESET.add("skr");
		EXHAUSTIVESET.add("brk");
		EXHAUSTIVESET.add("brky");
		EXHAUSTIVESET.add("bsk");
		EXHAUSTIVESET.add("bsky");
		EXHAUSTIVESET.add("bskr");
		EXHAUSTIVESET.add("kh");
		EXHAUSTIVESET.add("khw");
		EXHAUSTIVESET.add("khy");
		EXHAUSTIVESET.add("khr");
		EXHAUSTIVESET.add("mkh");
		EXHAUSTIVESET.add("mkhy");
		EXHAUSTIVESET.add("mkhr");
		EXHAUSTIVESET.add("vkh");
		EXHAUSTIVESET.add("vkhy");
		EXHAUSTIVESET.add("vkhr");
		EXHAUSTIVESET.add("ɡ");
		EXHAUSTIVESET.add("ɡw");
		EXHAUSTIVESET.add("ɡy");
		EXHAUSTIVESET.add("ɡr");
		EXHAUSTIVESET.add("ɡrw");
		EXHAUSTIVESET.add("ɡl");
		EXHAUSTIVESET.add("dɡ");
		EXHAUSTIVESET.add("dɡy");
		EXHAUSTIVESET.add("dɡr");
		EXHAUSTIVESET.add("bɡ");
		EXHAUSTIVESET.add("bɡy");
		EXHAUSTIVESET.add("bɡr");
		EXHAUSTIVESET.add("mɡ");
		EXHAUSTIVESET.add("mɡy");
		EXHAUSTIVESET.add("mɡr");
		EXHAUSTIVESET.add("vɡ");
		EXHAUSTIVESET.add("vɡy");
		EXHAUSTIVESET.add("vɡr");
		EXHAUSTIVESET.add("rɡ");
		EXHAUSTIVESET.add("rɡy");
		EXHAUSTIVESET.add("lɡ");
		EXHAUSTIVESET.add("sɡ");
		EXHAUSTIVESET.add("sɡy");
		EXHAUSTIVESET.add("sɡr");
		EXHAUSTIVESET.add("brɡ");
		EXHAUSTIVESET.add("brɡy");
		EXHAUSTIVESET.add("bsɡ");
		EXHAUSTIVESET.add("bsɡy");
		EXHAUSTIVESET.add("bsɡr");
		EXHAUSTIVESET.add("nɡ");
		EXHAUSTIVESET.add("dnɡ");
		EXHAUSTIVESET.add("mnɡ");
		EXHAUSTIVESET.add("rnɡ");
		EXHAUSTIVESET.add("lnɡ");
		EXHAUSTIVESET.add("snɡ");
		EXHAUSTIVESET.add("brnɡ");
		EXHAUSTIVESET.add("bsnɡ");
		EXHAUSTIVESET.add("c");
		EXHAUSTIVESET.add("ɡc");
		EXHAUSTIVESET.add("bc");
		EXHAUSTIVESET.add("lc");
		EXHAUSTIVESET.add("ch");
		EXHAUSTIVESET.add("mch");
		EXHAUSTIVESET.add("vch");
		EXHAUSTIVESET.add("j");
		EXHAUSTIVESET.add("mj");
		EXHAUSTIVESET.add("vj");
		EXHAUSTIVESET.add("rj");
		EXHAUSTIVESET.add("lj");
		EXHAUSTIVESET.add("brj");
		EXHAUSTIVESET.add("ny");
		EXHAUSTIVESET.add("nyw");
		EXHAUSTIVESET.add("ɡny");
		EXHAUSTIVESET.add("mny");
		EXHAUSTIVESET.add("rny");
		EXHAUSTIVESET.add("sny");
		EXHAUSTIVESET.add("brny");
		EXHAUSTIVESET.add("bsny");
		EXHAUSTIVESET.add("t");
		EXHAUSTIVESET.add("tr");
		EXHAUSTIVESET.add("ɡt");
		EXHAUSTIVESET.add("bt");
		EXHAUSTIVESET.add("rt");
		EXHAUSTIVESET.add("lt");
		EXHAUSTIVESET.add("st");
		EXHAUSTIVESET.add("brt");
		EXHAUSTIVESET.add("blt");
		EXHAUSTIVESET.add("bst");
		EXHAUSTIVESET.add("th");
		EXHAUSTIVESET.add("mth");
		EXHAUSTIVESET.add("vth");
		EXHAUSTIVESET.add("d");
		EXHAUSTIVESET.add("dw");
		EXHAUSTIVESET.add("dr");
		EXHAUSTIVESET.add("drw");
		EXHAUSTIVESET.add("ɡd");
		EXHAUSTIVESET.add("bd");
		EXHAUSTIVESET.add("md");
		EXHAUSTIVESET.add("vd");
		EXHAUSTIVESET.add("vdr");
		EXHAUSTIVESET.add("rd");
		EXHAUSTIVESET.add("ld");
		EXHAUSTIVESET.add("sd");
		EXHAUSTIVESET.add("brd");
		EXHAUSTIVESET.add("bld");
		EXHAUSTIVESET.add("bsd");
		EXHAUSTIVESET.add("n");
		EXHAUSTIVESET.add("ɡn");
		EXHAUSTIVESET.add("mn");
		EXHAUSTIVESET.add("rn");
		EXHAUSTIVESET.add("sn");
		EXHAUSTIVESET.add("brn");
		EXHAUSTIVESET.add("bsn");
		EXHAUSTIVESET.add("p");
		EXHAUSTIVESET.add("pr");
		EXHAUSTIVESET.add("dp");
		EXHAUSTIVESET.add("dpy");
		EXHAUSTIVESET.add("dpr");
		EXHAUSTIVESET.add("lp");
		EXHAUSTIVESET.add("sp");
		EXHAUSTIVESET.add("spy");
		EXHAUSTIVESET.add("spr");
		EXHAUSTIVESET.add("ph");
		EXHAUSTIVESET.add("phy");
		EXHAUSTIVESET.add("phyw");
		EXHAUSTIVESET.add("phr");
		EXHAUSTIVESET.add("vph");
		EXHAUSTIVESET.add("vphy");
		EXHAUSTIVESET.add("vphr");
		EXHAUSTIVESET.add("b");
		EXHAUSTIVESET.add("by");
		EXHAUSTIVESET.add("br");
		EXHAUSTIVESET.add("bl");
		EXHAUSTIVESET.add("db");
		EXHAUSTIVESET.add("dby");
		EXHAUSTIVESET.add("dbr");
		EXHAUSTIVESET.add("vb");
		EXHAUSTIVESET.add("vby");
		EXHAUSTIVESET.add("vbr");
		EXHAUSTIVESET.add("rb");
		EXHAUSTIVESET.add("lb");
		EXHAUSTIVESET.add("sb");
		EXHAUSTIVESET.add("sby");
		EXHAUSTIVESET.add("sbr");
		EXHAUSTIVESET.add("m");
		EXHAUSTIVESET.add("my");
		EXHAUSTIVESET.add("dm");
		EXHAUSTIVESET.add("dmy");
		EXHAUSTIVESET.add("rm");
		EXHAUSTIVESET.add("rmy");
		EXHAUSTIVESET.add("sm");
		EXHAUSTIVESET.add("smy");
		EXHAUSTIVESET.add("smr");
		EXHAUSTIVESET.add("ts");
		EXHAUSTIVESET.add("ɡts");
		EXHAUSTIVESET.add("bts");
		EXHAUSTIVESET.add("rts");
		EXHAUSTIVESET.add("rtsw");
		EXHAUSTIVESET.add("sts");
		EXHAUSTIVESET.add("brts");
		EXHAUSTIVESET.add("bsts");
		EXHAUSTIVESET.add("tsh");
		EXHAUSTIVESET.add("tshw");
		EXHAUSTIVESET.add("mtsh");
		EXHAUSTIVESET.add("vtsh");
		EXHAUSTIVESET.add("dz");
		EXHAUSTIVESET.add("mdz");
		EXHAUSTIVESET.add("vdz");
		EXHAUSTIVESET.add("rdz");
		EXHAUSTIVESET.add("brdz");
		EXHAUSTIVESET.add("w");
		EXHAUSTIVESET.add("zh");
		EXHAUSTIVESET.add("zhw");
		EXHAUSTIVESET.add("ɡzh");
		EXHAUSTIVESET.add("bzh");
		EXHAUSTIVESET.add("z");
		EXHAUSTIVESET.add("zw");
		EXHAUSTIVESET.add("zl");
		EXHAUSTIVESET.add("ɡz");
		EXHAUSTIVESET.add("bz");
		EXHAUSTIVESET.add("bzl");
		EXHAUSTIVESET.add("v");
		EXHAUSTIVESET.add("y");
		EXHAUSTIVESET.add("ɡy");
		EXHAUSTIVESET.add("r");
		EXHAUSTIVESET.add("rw");
		EXHAUSTIVESET.add("rl");
		EXHAUSTIVESET.add("brl");
		EXHAUSTIVESET.add("l");
		EXHAUSTIVESET.add("lw");
		EXHAUSTIVESET.add("sh");
		EXHAUSTIVESET.add("shw");
		EXHAUSTIVESET.add("ɡsh");
		EXHAUSTIVESET.add("bsh");
		EXHAUSTIVESET.add("s");
		EXHAUSTIVESET.add("sr");
		EXHAUSTIVESET.add("sl");
		EXHAUSTIVESET.add("ɡs");
		EXHAUSTIVESET.add("bs");
		EXHAUSTIVESET.add("bsw");
		EXHAUSTIVESET.add("bsr");
		EXHAUSTIVESET.add("bsl");
		EXHAUSTIVESET.add("h");
		EXHAUSTIVESET.add("hw");
		EXHAUSTIVESET.add("hr");
		EXHAUSTIVESET.add("lh");
	}
	
}
